---
title: "explore"
author: "Jake Eisaguirre"
date: "6/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(janitor)
library(sf)
library(lubridate)
library(leaflet)
library(sp)
library(RPostgreSQL)
library(rstudioapi)
library(DBI)
library(RPostgres)
```



```{r}

spec <- shiny_data %>% 
  group_by(id, date) %>% 
  filter(visual_life_stage == "adult")
```


```{r}
sf_ves <- st_as_sf(clean_ves_data, coords = c('utme', 'utmn'), crs = "+proj=utm +zone=11")

leaf_ves = st_transform(sf_ves, crs = "+proj=longlat +ellps=WGS84 +datum=WGS84")


coord <- leaf_ves %>% 
  mutate(long = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) %>% 
  as.data.frame() 


```


```{r}

leaf_bd <- clean_bd_data %>% 
  filter(wilderness == "yosemite",
        date == "2019")

leaf_test <- coord %>% 
  filter(wilderness == "yosemite")

leaflet() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  addPolygons(data = wilderness_shape)

```

```{r}

yos <- read_sf(here("data", "Yosemite", "yosemite.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

seq <- read_sf(here("data", "seq_king", "Sequoia_Kings_Canyon.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

king <- read_sf(here("data", "seq_king", "Sequoia_Kings_Canyon.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

troot <- read_sf(here("data", "Golden_Trout", "Golden_Trout.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

john <- read_sf(here("data", "John_Muir", "John_Muir.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

hoov <- read_sf(here("data", "Hoover", "Hoover.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

des <- read_sf(here("data", "Desolation", "Desolation.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)



adam <- read_sf(here("data", "Ansel_Adams", "Ansel_Adams.shp")) %>% 
  select(c(NAME_ABBRE, geometry)) %>% 
  rename(name = NAME_ABBRE)

wilderness_shape <- bind_rows(yos, seq, king, troot, john, hoov, des, adam)

wild_names <- data.frame(names = c("yosemite", "kings_canyon", "sequoia", "golden_trout", 
                                  "john_muir", "hoover", "desolation", "ansel_adams"))

wilderness_shape <- bind_cols(wilderness_shape, wild_names) %>% 
  select(!c(name))

wilderness_shape = st_transform(wilderness_shape, crs = "+proj=longlat +ellps=WGS84 +datum=WGS84")

st_write(wilderness_shape, here("data", "wilderness_shapes", "wilderness.shp"))

```
```{r}

t <- bd_data %>% 
  filter(date %in% c(2018:2021), wilderness == "yosemite", species == "ramu", visual_life_stage == "adult", id == "70449") %>% 
  group_by() %>% 
  mutate(med_bd = median(bd))

ggplot(data = t) +
  geom_line(aes(x=date, y = bd)) +
  geom_point(aes(x=date, y = bd))


a <- bd_data %>% 
        dplyr::filter(date >= 2016 & date <= 2021, wilderness == "yosemite", species == "ramu", 
                      visual_life_stage == "adult", id == "70499")

dput <- bd_data %>% 
  select(!c(lat, long))

dump(dput)

a <- ves_data %>% 
  filter(date %in% c(2010:2021),
         wilderness == "yosemite",
         species == "ramu",
         id == 70449) %>%
  group_by(visual_life_stage) %>% 
  summarise(count = sum(count))
  

dput(dput)
```
```{r}

bd_data <- structure(list(id = c(10008, 10008,10008), date = c(2018,2019,2020), species = c("ramu", "ramu", "ramu"),
                          wilderness = c("yosemite", "yosemite", "yosemite"), visual_life_stage = c("adult", "adult", "adult"),
                          bd = c(1,2,3)))

v <- ves_data %>% 
  filter(date %in% c(2016:2021),
         wilderness == "Yosemite",
         species == "Ramu",
         id == "70550",
         visual_life_stage %in% c("Tadpole", "Adult", "Subadult", "Eggmass")) %>% 
  arrange(visual_life_stage)

ggplot(data = v, aes(x= date, y = count, fill = visual_life_stage)) +
  geom_line()

prev <- des_bind %>% 
  mutate(long = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) %>% 
  as.data.frame() %>% 
  dplyr::select(!c(geometry)) %>% 
  rename(visual_life_stage = capture_life_stage) %>% 
  mutate(wilderness = gsub("_", " ", wilderness),
         wilderness = str_to_title(wilderness),
         visual_life_stage = str_to_title(visual_life_stage),
         species = str_to_title(species)) %>% 
  group_by(id, species, month_year, visual_life_stage) %>% 
  mutate(infect = if_else(bd_load>0, 1, 0)) %>% 
  summarise(sum_infect = (sum(infect)/sum(n())))

```

```{r}

lakes <- read_sf(here("data", "lakes", "lakes2021.shp")) %>% 
  mutate(geometry = st_transform(geometry, crs = 4326))

write_sf(lakes, here("data", "lakes", "lakes2021.shp"))

plot(lakes)

 view <- shape %>% 
      filter(wilderness == "Yosemite") %>% 
      st_bbox(geometry) %>% 
   as.vector()
 
 yos <- read_sf(here("data", "wilderness_shapes", "yos", "yose_kica_sequ_boundaries.shp")) %>% 
   select(UNIT_NAME, geometry) %>% 
   rename(names = UNIT_NAME) %>% 
   mutate(names = case_when(names == "Yosemite National Park" ~ "yosemite",
                            names == "Kings Canyon National Park" ~ "kings_canyon",
                            names == "Sequoia National Park" ~ "sequoia")) %>% 
   st_transform(crs = 4326)
 
 
 shape <- read_sf(here("data", "wilderness_shapes", "wilderness.shp")) %>% 
   filter(!names %in% c("sequoia", "kings_canyon", "yosemite")) %>% 
   st_transform(crs = 4326) %>% 
   rbind(yos)
 
write_sf(shape, here("data", "wilderness_shapes", "wilderness.shp"), overwrite = T)
```
```{r}

usfs <- read_sf(here("data", "temp_shapes", "usfs-boundaries", "S_USA.AdministrativeForest.shp"))

mylf <- read_sf(here("data", "temp_shapes", "mylf-range-map", "RK_mylf_boundary_final.shp"))

frog <- read_sf(here("data", "temp_shapes", "frog-conservation-areas", "FCA_RMUSCOSA_RSIERRAE_020618.shp"))

cdfw <- read_sf(here("data", "temp_shapes", "cdfw-boundaries", "CDFW_Regions.shp"))

ca <- read_sf(here("data", "temp_shapes", "ca-boundaries", "CA_boundary_NAD83albers.shp"))
  
plot(usfs$geometry[FORESTNAME == "Sierra National Forest"])
```
```{r}


test <- bd_plot %>% 
        dplyr::filter(date <= 2021 & date >= 2016, 
                      wilderness == "Yosemite", 
                      species == "Mountain yellow-legged frog - Rana muscosa", 
                      id == "70449") %>% 
        mutate("Year-Month" = month_year,
               "Log(Bd) Load" = bd,
               "Visual Life Stage" = visual_life_stage,
               Prevalence = round(Prevalence, 2),
               bd = round(bd, 2))

ggplot(data = test, aes(x = month_year, y = bd, fill = visual_life_stage, group = 1)) +
        geom_point(size = 2.5, color = "#fde725") +
        geom_smooth(se = F, show.legend = F) +
        ylab("Median log10(Bd)") +
        xlab("Year-Month") +
        labs(fill = "Visual Life Stage") + 
        geom_text_repel(aes(label = paste(round(test$sample_size, 3)))) +
        theme_classic() +
        theme(#plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust = 0.9, size = 12),
          plot.title = element_text(hjust = 0.5, vjust = 1.2, size = 17),
          axis.line = element_line(size = 1.1),
          axis.ticks = element_line(size = 1.8),
          axis.text.y = element_text(size = 14),
          axis.title.x = element_text(size = 14, vjust = 1),
          axis.title.y = element_text(size = 15),
          legend.key.height = unit(2, "cm"),
          legend.title = element_text(size = 15),
          legend.text = element_text(size = 15),
          legend.key.size = unit(2, "cm")) +
        scale_y_continuous(breaks = integer_breaks()) +
        #scale_fill_manual(values = c("Subadult" = "#fde725"),
                           #name = "Visual Life Stage") +
        geom_hline(yintercept=5.8, linetype='dotted', col = 'red')

```

